# Generated by Django 2.2.1 on 2019-05-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_age',
        ),
    ]
